"""add alert_configs table

Revision ID: b21bc001d252
Revises: b8ff8c6d9ea9
Create Date: 2025-10-18 16:22:01.305870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21bc001d252'
down_revision: Union[str, None] = 'b8ff8c6d9ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('slack_webhook_url', sa.String(), nullable=True),
    sa.Column('slack_enabled', sa.Boolean(), nullable=False),
    sa.Column('hallucination_threshold', sa.Float(), nullable=False),
    sa.Column('hallucination_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_cost_budget_usd', sa.Float(), nullable=True),
    sa.Column('cost_spike_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('latency_p95_threshold_ms', sa.Integer(), nullable=True),
    sa.Column('latency_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_configs')
    # ### end Alembic commands ###
